# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 655f7d4f5c000c854239add9d5d5b86c35ba9f58a93daebb4c1359a181d9d92ac32add0bea74a23cf33edc82ba90f967e188fd6df93f523f051fe72147cbfbdc

test:
  secret_key_base: 2d195da4ed6258a20a95057e6e15827e6daa203bd9ee5fe6ae3df6be940ed2b955219a220ee7ac5b9132e9a52895981ae6bd280cf6a2739b2ba0b8efc36c61f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
